"""init tables

Revision ID: 7e5bf07cf526
Revises: 
Create Date: 2026-07-22 16:07:40.698961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector


# revision identifiers, used by Alembic.
revision: str = '7e5bf07cf526'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilisateurs_email'), 'utilisateurs', ['email'], unique=True)
    op.create_index(op.f('ix_utilisateurs_id'), 'utilisateurs', ['id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('secteur_activite', sa.String(), nullable=True),
    sa.Column('specialite', sa.String(), nullable=True),
    sa.Column('zone_geographique', sa.String(), nullable=True),
    sa.Column('nom_sous_domaine', sa.String(), nullable=True),
    sa.Column('statut_abonnement', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom_sous_domaine'),
    sa.UniqueConstraint('utilisateur_id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_table('abonnements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.TIMESTAMP(), nullable=False),
    sa.Column('date_fin', sa.TIMESTAMP(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_index(op.f('ix_abonnements_id'), 'abonnements', ['id'], unique=False)
    op.create_table('contenus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('titre', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('date_creation', sa.TIMESTAMP(), server_default='now()', nullable=True),
    sa.Column('date_publication', sa.TIMESTAMP(), nullable=True),
    sa.Column('date_validation', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_contenus_id'), 'contenus', ['id'], unique=False)
    op.create_table('reseaux_sociaux_connexions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('plateforme', sa.String(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('expire_le', sa.TIMESTAMP(), nullable=True),
    sa.Column('date_connexion', sa.TIMESTAMP(), server_default='now()', nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reseaux_sociaux_connexions_id'), 'reseaux_sociaux_connexions', ['id'], unique=False)
    op.create_table('embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contenu_id', sa.Integer(), nullable=False),
    sa.Column('vecteur', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.ForeignKeyConstraint(['contenu_id'], ['contenus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contenu_id')
    )
    op.create_index(op.f('ix_embeddings_id'), 'embeddings', ['id'], unique=False)
    op.create_table('metriques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contenu_id', sa.Integer(), nullable=False),
    sa.Column('plateforme', sa.String(), nullable=False),
    sa.Column('vues', sa.Integer(), nullable=True),
    sa.Column('donnees_specifiques', sa.JSON(), nullable=True),
    sa.Column('date_mesure', sa.TIMESTAMP(), server_default='now()', nullable=True),
    sa.ForeignKeyConstraint(['contenu_id'], ['contenus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metriques_id'), 'metriques', ['id'], unique=False)
    op.create_table('mots_cles_recherches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('mot_cle', sa.String(), nullable=False),
    sa.Column('volume_recherche', sa.Integer(), nullable=True),
    sa.Column('difficulte', sa.Float(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.Column('contenu_id', sa.Integer(), nullable=True),
    sa.Column('date_recherche', sa.TIMESTAMP(), server_default='now()', nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['contenu_id'], ['contenus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mots_cles_recherches_id'), 'mots_cles_recherches', ['id'], unique=False)
    op.create_table('prompts_historique',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contenu_id', sa.Integer(), nullable=False),
    sa.Column('mot_cle_id', sa.Integer(), nullable=True),
    sa.Column('parametres', sa.JSON(), nullable=True),
    sa.Column('origine', sa.String(), nullable=True),
    sa.Column('score_performance', sa.Float(), nullable=True),
    sa.Column('date_creation', sa.TIMESTAMP(), server_default='now()', nullable=True),
    sa.ForeignKeyConstraint(['contenu_id'], ['contenus.id'], ),
    sa.ForeignKeyConstraint(['mot_cle_id'], ['mots_cles_recherches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompts_historique_id'), 'prompts_historique', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompts_historique_id'), table_name='prompts_historique')
    op.drop_table('prompts_historique')
    op.drop_index(op.f('ix_mots_cles_recherches_id'), table_name='mots_cles_recherches')
    op.drop_table('mots_cles_recherches')
    op.drop_index(op.f('ix_metriques_id'), table_name='metriques')
    op.drop_table('metriques')
    op.drop_index(op.f('ix_embeddings_id'), table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_index(op.f('ix_reseaux_sociaux_connexions_id'), table_name='reseaux_sociaux_connexions')
    op.drop_table('reseaux_sociaux_connexions')
    op.drop_index(op.f('ix_contenus_id'), table_name='contenus')
    op.drop_table('contenus')
    op.drop_index(op.f('ix_abonnements_id'), table_name='abonnements')
    op.drop_table('abonnements')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_utilisateurs_id'), table_name='utilisateurs')
    op.drop_index(op.f('ix_utilisateurs_email'), table_name='utilisateurs')
    op.drop_table('utilisateurs')
    # ### end Alembic commands ###
